name: JML Validation

on:
  push:
  pull_request:

jobs:
  jml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run OpenJML
        run: echo "JML check here"

          ./run_openjml.sh
<<<<<<< HEAD
=======

>>>>>>> 452610b (Add JML verification with OpenJML in GitHub Actions)
